#!/bin/sh
if [ "$1" = "indextargets" ]; then
	cat <<'EOT'
/var/lib/apt/lists/deb.debian.org_debian_dists_unstable_main_binary-amd64_Packages.gz
EOT
else
	echo "E: invalid operation" >&2
	echo "$@" >&2
	exit 1
fi
